# Generated by Django 4.0.3 on 2022-04-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accident',
            fields=[
                ('accid', models.AutoField(primary_key=True, serialize=False)),
                ('accidenttype', models.CharField(max_length=100, verbose_name='accidenttype')),
                ('accident', models.CharField(max_length=300, verbose_name='accident')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('date', models.CharField(max_length=50, verbose_name='date')),
                ('time', models.CharField(max_length=50, verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='ambulance',
            fields=[
                ('ambid', models.AutoField(primary_key=True, serialize=False)),
                ('ambname', models.CharField(max_length=100, verbose_name='ambname')),
                ('ambaddress', models.CharField(max_length=100, verbose_name='ambaddress')),
                ('amblocation', models.CharField(max_length=100, verbose_name='amblocation')),
                ('clocation', models.CharField(max_length=100, verbose_name='clocation')),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('hospid', models.AutoField(primary_key=True, serialize=False)),
                ('hospname', models.CharField(max_length=100, verbose_name='hospname')),
                ('hospdesc', models.CharField(max_length=300, verbose_name='hospdesc')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('role', models.CharField(max_length=10, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='police',
            fields=[
                ('policeid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('address', models.CharField(max_length=300, verbose_name='address')),
                ('location', models.CharField(max_length=300, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='username')),
                ('phone', models.CharField(max_length=100, verbose_name='userphone')),
                ('email', models.CharField(max_length=100, verbose_name='useremail')),
                ('address', models.CharField(max_length=300, verbose_name='useraddress')),
                ('pin', models.CharField(max_length=300, verbose_name='pin')),
                ('date', models.CharField(max_length=30, verbose_name='date')),
                ('status', models.CharField(max_length=30, verbose_name='status')),
                ('emergency', models.CharField(max_length=100, verbose_name='emergency')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crisis.login')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staffid', models.AutoField(primary_key=True, serialize=False)),
                ('staffname', models.CharField(max_length=100, verbose_name='staffname')),
                ('staffaddress', models.CharField(max_length=100, verbose_name='staffaddress')),
                ('staffphone', models.CharField(max_length=100, verbose_name='staffphone')),
                ('staffdesc', models.CharField(max_length=100, verbose_name='staffdesc')),
                ('staffdepart', models.CharField(max_length=100, verbose_name='staffdepart')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crisis.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('docid', models.AutoField(primary_key=True, serialize=False)),
                ('docname', models.CharField(max_length=100, verbose_name='docname')),
                ('docdesc', models.CharField(max_length=300, verbose_name='docdesc')),
                ('department', models.CharField(max_length=300, verbose_name='department')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crisis.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('compid', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=300, verbose_name='complaint')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crisis.user')),
            ],
        ),
    ]
