# Generated by Django 4.0.3 on 2022-04-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0004_alter_staff_staffdepart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulance',
            old_name='ambaddress',
            new_name='ambphone',
        ),
    ]
