# Generated by Django 4.0.3 on 2022-04-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0005_rename_ambaddress_ambulance_ambphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crisis.police'),
        ),
        migrations.AddField(
            model_name='accident',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crisis.user'),
        ),
    ]
